package manageInventory;

import java.util.ArrayList;
import java.util.Locale.Category;

import javax.swing.text.html.HTMLDocument.HTMLReader.SpecialAction;

public class Vehicle {
	
	private long id; // VIN is generated by the system or provided by the dealer???
	private int year;
	private String webId, category, make, model, trim, type;
	private double price;
	//private ArrayList<Special> specials = new ArrayList<Special>();
	
	// getter and setter
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public int getYear() {
		return year;
	}
	public void setYear(int year) {
		this.year = year;
	}
	public String getWebId() {
		return webId;
	}
	public void setWebId(String webId) {
		this.webId = webId;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getMake() {
		return make;
	}
	public void setMake(String make) {
		this.make = make;
	}
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	public String getTrim() {
		return trim;
	}
	public void setTrim(String trim) {
		this.trim = trim;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	// end of getter and setter
	
//	public double getFinalPrice(){
//		for(Special s : specials){
//			price -= s.discount;
//		}
//	}
}
